'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly:System.Data.Objects.DataClasses.EdmSchemaAttribute()>
Namespace XtraGridDataServiceExample.Service

'#Region "Contexts"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NorthwindEntities
        Inherits System.Data.Objects.ObjectContext

'#Region "Constructors"
        ''' <summary>
        ''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NorthwindEntities", "NorthwindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NorthwindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "NorthwindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

'#End Region
'#Region "Partial Methods"
        Partial Private Sub OnContextCreated()
        End Sub

'#End Region
'#Region "ObjectSet Properties"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Products As ObjectSet(Of XtraGridDataServiceExample.Service.Product)
            Get
                If(Me._Products Is Nothing) Then
                    Me._Products = Me.CreateObjectSet(Of XtraGridDataServiceExample.Service.Product)("Products")
                End If

                Return Me._Products
            End Get
        End Property

        Private _Products As System.Data.Objects.ObjectSet(Of XtraGridDataServiceExample.Service.Product)

'#End Region
'#Region "AddTo Methods"
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt; T&gt;  property instead.
        ''' </summary>
        Public Sub AddToProducts(ByVal product As XtraGridDataServiceExample.Service.Product)
            Me.AddObject("Products", product)
        End Sub
'#End Region
    End Class

'#End Region
'#Region "Entities"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Product")>
    <System.SerializableAttribute()>
    <System.Runtime.Serialization.DataContractAttribute(IsReference:=True)>
    Public Partial Class Product
        Inherits System.Data.Objects.DataClasses.EntityObject

'#Region "Factory Method"
        ''' <summary>
        ''' Create a new Product object.
        ''' </summary>
        ''' <param name="productID">Initial value of the ProductID property.</param>
        ''' <param name="productName">Initial value of the ProductName property.</param>
        ''' <param name="discontinued">Initial value of the Discontinued property.</param>
        Public Shared Function CreateProduct(ByVal productID As Global.System.Int32, ByVal productName As Global.System.[String], ByVal discontinued As Global.System.[Boolean]) As Product
            Dim product As XtraGridDataServiceExample.Service.Product = New XtraGridDataServiceExample.Service.Product()
            product.ProductID = productID
            product.ProductName = productName
            product.Discontinued = discontinued
            Return product
        End Function

'#End Region
'#Region "Primitive Properties"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductID As Global.System.Int32
            Get
                Return Me._ProductID
            End Get

            Set(ByVal value As Global.System.Int32)
                If Me._ProductID <> value Then
                    Me.OnProductIDChanging(value)
                    Me.ReportPropertyChanging("ProductID")
                    Me._ProductID = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                    Me.ReportPropertyChanged("ProductID")
                    Me.OnProductIDChanged()
                End If
            End Set
        End Property

        Private _ProductID As Global.System.Int32

        Partial Private Sub OnProductIDChanging(ByVal value As Global.System.Int32)
        End Sub

        Partial Private Sub OnProductIDChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductName As Global.System.[String]
            Get
                Return Me._ProductName
            End Get

            Set(ByVal value As Global.System.[String])
                Me.OnProductNameChanging(value)
                Me.ReportPropertyChanging("ProductName")
                Me._ProductName = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
                Me.ReportPropertyChanged("ProductName")
                Me.OnProductNameChanged()
            End Set
        End Property

        Private _ProductName As Global.System.[String]

        Partial Private Sub OnProductNameChanging(ByVal value As Global.System.[String])
        End Sub

        Partial Private Sub OnProductNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property SupplierID As Nullable(Of Global.System.Int32)
            Get
                Return Me._SupplierID
            End Get

            Set(ByVal value As Nullable(Of Global.System.Int32))
                Me.OnSupplierIDChanging(value)
                Me.ReportPropertyChanging("SupplierID")
                Me._SupplierID = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("SupplierID")
                Me.OnSupplierIDChanged()
            End Set
        End Property

        Private _SupplierID As System.Nullable(Of Global.System.Int32)

        Partial Private Sub OnSupplierIDChanging(ByVal value As System.Nullable(Of Global.System.Int32))
        End Sub

        Partial Private Sub OnSupplierIDChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property CategoryID As Nullable(Of Global.System.Int32)
            Get
                Return Me._CategoryID
            End Get

            Set(ByVal value As Nullable(Of Global.System.Int32))
                Me.OnCategoryIDChanging(value)
                Me.ReportPropertyChanging("CategoryID")
                Me._CategoryID = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("CategoryID")
                Me.OnCategoryIDChanged()
            End Set
        End Property

        Private _CategoryID As System.Nullable(Of Global.System.Int32)

        Partial Private Sub OnCategoryIDChanging(ByVal value As System.Nullable(Of Global.System.Int32))
        End Sub

        Partial Private Sub OnCategoryIDChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property QuantityPerUnit As Global.System.[String]
            Get
                Return Me._QuantityPerUnit
            End Get

            Set(ByVal value As Global.System.[String])
                Me.OnQuantityPerUnitChanging(value)
                Me.ReportPropertyChanging("QuantityPerUnit")
                Me._QuantityPerUnit = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
                Me.ReportPropertyChanged("QuantityPerUnit")
                Me.OnQuantityPerUnitChanged()
            End Set
        End Property

        Private _QuantityPerUnit As Global.System.[String]

        Partial Private Sub OnQuantityPerUnitChanging(ByVal value As Global.System.[String])
        End Sub

        Partial Private Sub OnQuantityPerUnitChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property UnitPrice As Nullable(Of Global.System.[Decimal])
            Get
                Return Me._UnitPrice
            End Get

            Set(ByVal value As Nullable(Of Global.System.[Decimal]))
                Me.OnUnitPriceChanging(value)
                Me.ReportPropertyChanging("UnitPrice")
                Me._UnitPrice = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitPrice")
                Me.OnUnitPriceChanged()
            End Set
        End Property

        Private _UnitPrice As System.Nullable(Of Global.System.[Decimal])

        Partial Private Sub OnUnitPriceChanging(ByVal value As System.Nullable(Of Global.System.[Decimal]))
        End Sub

        Partial Private Sub OnUnitPriceChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property UnitsInStock As Nullable(Of Global.System.Int16)
            Get
                Return Me._UnitsInStock
            End Get

            Set(ByVal value As Nullable(Of Global.System.Int16))
                Me.OnUnitsInStockChanging(value)
                Me.ReportPropertyChanging("UnitsInStock")
                Me._UnitsInStock = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitsInStock")
                Me.OnUnitsInStockChanged()
            End Set
        End Property

        Private _UnitsInStock As System.Nullable(Of Global.System.Int16)

        Partial Private Sub OnUnitsInStockChanging(ByVal value As System.Nullable(Of Global.System.Int16))
        End Sub

        Partial Private Sub OnUnitsInStockChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property UnitsOnOrder As Nullable(Of Global.System.Int16)
            Get
                Return Me._UnitsOnOrder
            End Get

            Set(ByVal value As Nullable(Of Global.System.Int16))
                Me.OnUnitsOnOrderChanging(value)
                Me.ReportPropertyChanging("UnitsOnOrder")
                Me._UnitsOnOrder = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitsOnOrder")
                Me.OnUnitsOnOrderChanged()
            End Set
        End Property

        Private _UnitsOnOrder As System.Nullable(Of Global.System.Int16)

        Partial Private Sub OnUnitsOnOrderChanging(ByVal value As System.Nullable(Of Global.System.Int16))
        End Sub

        Partial Private Sub OnUnitsOnOrderChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ReorderLevel As Nullable(Of Global.System.Int16)
            Get
                Return Me._ReorderLevel
            End Get

            Set(ByVal value As Nullable(Of Global.System.Int16))
                Me.OnReorderLevelChanging(value)
                Me.ReportPropertyChanging("ReorderLevel")
                Me._ReorderLevel = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ReorderLevel")
                Me.OnReorderLevelChanged()
            End Set
        End Property

        Private _ReorderLevel As System.Nullable(Of Global.System.Int16)

        Partial Private Sub OnReorderLevelChanging(ByVal value As System.Nullable(Of Global.System.Int16))
        End Sub

        Partial Private Sub OnReorderLevelChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Discontinued As Global.System.[Boolean]
            Get
                Return Me._Discontinued
            End Get

            Set(ByVal value As Global.System.[Boolean])
                Me.OnDiscontinuedChanging(value)
                Me.ReportPropertyChanging("Discontinued")
                Me._Discontinued = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Discontinued")
                Me.OnDiscontinuedChanged()
            End Set
        End Property

        Private _Discontinued As Global.System.[Boolean]

        Partial Private Sub OnDiscontinuedChanging(ByVal value As Global.System.[Boolean])
        End Sub

        Partial Private Sub OnDiscontinuedChanged()
        End Sub
'#End Region
    End Class
'#End Region
End Namespace
